name: Deploy Ghost Theme (manual)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip theme folder
        run: |
          cd themes/Casper-main
          zip -r ../../theme.zip .

      - name: Deploy theme to Ghost
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: |
          curl -X POST "$GHOST_ADMIN_API_URL/ghost/api/admin/themes/upload/" \
            -H "Authorization: GhostAdminAPIKey $GHOST_ADMIN_API_KEY" \
            -F "file=@theme.zip"